project:
  customer: Orange Box
  project: Orange Box Demo
  opportunity: None
  sku: fcb-stable-yoga-jammy
  arch: custom-orangebox
  hw: approved
  config:
    fce_git_ref_hint: stable/latest
    fcbtest_snap_channel: latest/stable
  features:
    - stable
    - baseline
layers:
  - name: baremetal
    type: baremetal
    config:
      hosts:
        - hostname: ob24
          ip: 172.27.24.1
          zone: default
  - name: maas
    type: existing_maas
    parent: baremetal
    config:
      apikey_path: /config/api_maas
      api_url: http://172.27.24.1:5240/MAAS

  # - name: baremetal
  #   type: baremetal
  #   config:
  #     hosts: include-rel://config/hosts.yaml
  # - name: maas
  #   type: maas
  #   parent: baremetal
  #   config:
  #     tweaks:
  #       - nobond
  #       - nobridge
  #       - nomaasha
  #       - nopgha
  #       - nojujuha
  #     maas_vip: 172.27.80.1
  #     postgresql_vip: 172.27.80.1
  #     package_repositories:
  #       [] # optional dict
  #       # For params see: 'maas playground package-repositories create --help'
  #     maas_config: # optional dict
  #       # For params see: 'maas profile maas set-config --help'
  #       dnssec_validation: "no"
  #       upstream_dns: 8.8.8.8
  #       # If a proxy is required, set this
  #       # http_proxy: FCE_TEMPLATE
  #       # set this when a proxy server is configured for MAAS so that
  #       # MAAS acts as an intermediary for all nodes in the deployment
  #       # use_peer_proxy: true
  #       commissioning_distro_series: focal
  #     maas_boot_source_selections:
  #       - release: "focal"
  #         arches: ["amd64"]
  #       - release: "bionic"
  #         arches: ["amd64"]
  #     maas_admin: root
  #     maas_admin_email: root@localhost.localdomain
  #     maas_admin_password: root
  #     maas_admin_ssh_key: /home/ubuntu/.ssh/id_rsa.pub
  #     snap_channel: "3.3/stable"
  #     networks: include-rel://config/networks.yaml
  #     enlist_timeout: 1801
  #     nodeconfig: include-rel://config/bucketsconfig.yaml
  #     nodes: include-rel://config/nodes.yaml
  #     vms: include-rel://config/vms.yaml
  #     vmconfig: include-rel://config/vmsbucketsconfig.yaml
  #     domains:
  #       - name: orange.box
  #     dnsresources:
  #       - fqdn: aodh.orange.box
  #         ip_addresses: 172.27.80.21
  #       - fqdn: ceilometer.orange.box
  #         ip_addresses: 172.27.80.22
  #       - fqdn: cinder.orange.box
  #         ip_addresses: 172.27.80.23
  #       - fqdn: dashboard.orange.box
  #         ip_addresses: 172.27.80.24
  #       - fqdn: designate.orange.box
  #         ip_addresses: 172.27.80.25
  #       - fqdn: glance.orange.box
  #         ip_addresses: 172.27.80.26
  #       - fqdn: gnocchi.orange.box
  #         ip_addresses: 172.27.80.27
  #       - fqdn: heat.orange.box
  #         ip_addresses: 172.27.80.28
  #       - fqdn: keystone.orange.box
  #         ip_addresses: 172.27.80.29
  #       - fqdn: neutron.orange.box
  #         ip_addresses: 172.27.80.31
  #       - fqdn: nova.orange.box
  #         ip_addresses: 172.27.80.32
  #       - fqdn: radosgw.orange.box
  #         ip_addresses: 172.27.80.33
  #       - fqdn: masakari.orange.box
  #         ip_addresses: 172.27.80.34
  #       - fqdn: placement.orange.box
  #         ip_addresses: 172.27.80.35
  #       - fqdn: vault.orange.box
  #         ip_addresses: 172.27.80.36
  #       - fqdn: barbican.orange.box
  #         ip_addresses: 172.27.80.37
  #       - fqdn: octavia.orange.box
  #         ip_addresses: 172.27.80.38
  #       - fqdn: manila.orange.box
  #         ip_addresses: 172.27.80.39
  #       - fqdn: ganesha.orange.box
  #         ip_addresses: 172.27.80.40
  #       - fqdn: magnum.orange.box
  #         ip_addresses: 172.27.80.41
  - name: juju_maas_controller
    type: juju_maas_controller
    parent: maas
    config:
      controller_name: maas
      model_defaults: # optional dict
        # see: 'juju model-config --help'
        # Use maas_vip as http_proxy (port 3128 for regular http and 8000 for packages)
        # apt-http-proxy: http://maas_vip:8000
        # apt-https-proxy: http://maas_vip:8000
        # snap-http-proxy: http://maas_vip:3128
        # snap-https-proxy: http://maas_vip:3128
        # juju-http-proxy: http://maas_vip:3128
        # juju-https-proxy: http://maas_vip:3128
        # NOTE: only use new-style no-proxy for MAAS/other provider hostnames
        # as juju-{http,https}-proxy settings appear as JUJU_CHARM_{HTTP,HTTPS}_PROXY,
        # not as {HTTP,HTTPS}_PROXY environment variables and do not affect hook environment
        # see https://git.io/fh5ky for more information
        # juju-no-proxy: FCE_TEMPLATE
        juju-no-proxy: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,127.0.0.1,localhost
        # XXX: 1891223
        # This value of 2000 comes from
        # https://linuxcontainers.org/lxd/docs/master/production-setup
        # The default is 200.
        cloudinit-userdata: |
          write_files:
            - content: |
                kernel.keys.maxkeys = 2000
                kernel.keys.maxbytes = 2000000
              owner: "root:root"
              path: /etc/sysctl.d/10-keys.conf
              permissions: "0644"
            - content: |
                set ignorecase
                set hlsearch
                set nu
                set lisp
                colorscheme ron
                set paste
              owner: "root:root"
              path: /etc/vim/vimrc.local
              permissions: '0644'
          postruncmd:
            - sysctl --system
      extra_options:
        bootstrap-series: focal #avoid jammy until ob is upgraded as well
  #  uncomment to include magpie
  #- include-rel://config/magpie.yaml


  - name: openstack
    type: openstack
    parent: juju_maas_controller
    features:
      - name: openstack-minimal
      - name: vault-fde
      - name: barbican
        #- name: octavia
      - name: telemetry
      - name: designate
      - name: ntp
        options:
          # Override those when there are more suitable NTP servers locally.
          # If a deployment is behind a proxy, you should remove the default
          # set of NTP servers on the Internet to avoid false positives.
          source: ""
          pools: "0.ubuntu.pool.ntp.org 1.ubuntu.pool.ntp.org 2.ubuntu.pool.ntp.org 3.ubuntu.pool.ntp.org ntp.ubuntu.com"
      - name: openstack
        options:
          openstack-origin: cloud:jammy-yoga
          dashboard-secret: include-file://../../secrets/openstack-dashboard-secret.txt
        #   # Warning: NEVER use direct drive references (as /dev/sda and so on),
        #   # as they are never guaranteed to be persistent across the reboots.
        #   # ephemeral-device: /dev/disk/by-dname/FCE_TEMPLATE
          flat-network-providers: physnet1
          vlan-ranges:
          dns-domain: "openstack.orangebox.lan."
          physical-network-mtus: physnet1:1500
          bridge-mappings: physnet1:br-data
          lb-mgmt-issuing-cacert: include-base64://../../tls/octavia/issuing_ca.pem
          lb-mgmt-issuing-ca-private-key: include-base64://../../tls/octavia/issuing_ca_key.pem
          lb-mgmt-issuing-ca-key-passphrase: foobar
          lb-mgmt-controller-cacert: include-base64://../../tls/octavia/controller_ca.pem
          lb-mgmt-controller-cert: include-base64://../../tls/octavia/controller_cert_bundle.pem
          designate-nameservers: "ns1.designate.orange.box."
          designate-bind_allowed_nets: ""
          designate-bind_forwarders: 172.27.80.1
      # - name: ha
      #   options:
      #     ha_count: 1
      # - name: ovn
      #   options:
      #     data-port: br-data:usb0
      # - name: ceph
      #   options:
      #     # Warning: NEVER use direct drive references, as /dev/sdX and so on,
      #     # because they are never guaranteed to be persistent across the reboots.
      #     osd-devices: /dev/disk/by-dname/sdb-part1
          # expected-osd-count: 3
    config:
      bundle_options:
        series: jammy
        binding_map:
          oam-space: oam-space
          admin-space: oam-space
          public-space: oam-space
          dns-access-space: oam-space
          internal-space: oam-space
          overlay-space: oam-space
          ceph-public-space: oam-space
          ceph-cluster-space: oam-space
      build_bundle: false
      juju_model: openstack
      model_config:
        default-space: oam-space
      bundles: # Primary bundle followed by optional overlays.
        #- TEST_min_openstack_2_nodes.yaml
        - minimal_ob_jammy_yoga_no_vault.yaml
        #- ob_jammy_yoga.yaml
        # - overlay-vips.yaml
        # - overlay-orangebox.yaml
        # - overlay-manila.yaml
          # only enable below if deploying COS
        - cos/grafana-agent-overlay.yaml
        - cos/cos-proxy-overlay.yaml
      # ha_type: use ssl if using SSL certs and hostnames, otherwise use dnsha, vip or none
      ha_type: none
        #      cacert: /home/ubuntu/camille/openstack/config/root-ca.crt
        #cacert: /home/ubuntu/snap/openstackclients/common/root-ca.crt
      openstack_config: include-rel://config/openstack.yaml
      retry_error_count: 5
      wait_exclude:
        - public-policy-routing
        - keystone-ldap
      applications:
        - name: vault
          wait_exclude:
            - barbican-vault
            - ceilometer
            - ceph-osd
            - ceph-radosgw
            - ceph-mon
            - cinder-ceph
            - glance
            - gnocchi
            - keystone-ldap # Not configured for Lab deployment
            - neutron-api-plugin-ovn
            - nova-compute
            - octavia
            - ovn-chassis-octavia
            - ovn-central
            - ovn-chassis
            - public-policy-routing # Not configured for Lab deployment
            - vault
        - name: ceilometer # XXX: 1822190
          wait_exclude:
            - ceilometer
        - name: octavia
          wait_exclude: ['octavia']
        - name: octaviadiskimageretrofit
          application: octavia-diskimage-retrofit
        - name: heat
        - name: cinder
        - name: designate
          config:
            set_dns_app: ["neutron-api-plugin-ovn"]


  - name: juju_openstack_controller
    type: juju_openstack_controller
    # parent: openstack
    parent: openstack
    config:
      # ha: 3
      # ha_timeout: 1200
      controller_name: foundation-openstack
      model_defaults: # optional dict
        # see: 'juju model-config --help'
        use-floating-ip: True
        # If a proxy is required, set it here
        # apt-http-proxy: FCE_TEMPLATE
        # apt-https-proxy: FCE_TEMPLATE
        # snap-http-proxy: FCE_TEMPLATE
        # snap-https-proxy: FCE_TEMPLATE
        automatically-retry-hooks: false
        # logging-config: <root>=DEBUG
        network: ubuntu-net
        external-network: ext-net
        cloudinit-userdata: |
          write_files:
            - content: |
                set ignorecase
                set hlsearch
                set lisp
                colorscheme ron
                set paste
              owner: "root:root"
              path: /etc/vim/vimrc.local
              permissions: '0644'
      extra_options:
        bootstrap-constraints: "cores=2 mem=4G"


  - name: microk8s
    type: microk8s
    parent: juju_maas_controller
    features:
    - name: automatic-placement
    - name: ntp
    - name: microk8s
      options:
        use_legacy_charm: false
        hostpath_storage: true
        baremetal_control_plane: true
        num_units_control_plane: 1
        baremetal_worker: true
        num_units_worker: 1
        # dns_forward: 172.27.24.1
        pools: '0.ubuntu.pool.ntp.org 1.ubuntu.pool.ntp.org 2.ubuntu.pool.ntp.org 3.ubuntu.pool.ntp.org ntp.ubuntu.com'
    config:
      bundle_options:
        series: jammy
        binding_map:
          oam-space: oam-space
          internal-space: oam-space
      build_bundle: false
      juju_model: microk8s
      model_config:
        default-space: oam-space
      bundles:
        - cos/microk8s.yaml

  - name: existing_juju_maas_controller_microk8s
    type: microk8s_cloud_on_existing_juju_controller
    parent: juju_maas_controller
    config:
      cloud_name: microk8s_cloud

  - name: metallb
    type: juju_kubernetes_workload
    parent: existing_juju_maas_controller_microk8s
    features:
    - name: metallb
    config:
      juju_model: metallb-system
      model_config: {}
      build_bundle: false
      trust_bundle: true
      bundle_options:
        series: jammy
      bundles: 
      - cos/metallb.yaml
      wait_exclude:
        - metallb-speaker

  # # enable hostpath storage manually
  # # microk8s enable hostpath-storage
  
  - name: juju_microk8s_controller
    type: juju_microk8s_controller
    parent: microk8s
    config:
      controller_name: microk8s-controller
      model_defaults:
        logging-config: <root>=DEBUG
        automatically-retry-hooks: true
      # change to ceph-xfs if using charmed Ceph + CSI or ceph-rbd if regular ceph
      storage_class: microk8s-hostpath
  
  - name: cos
    type: juju_kubernetes_workload
    parent: juju_microk8s_controller
    features:
      - name: cos-lite
    config:
      offers:
        - application: alertmanager
          endpoints:
          - karma-dashboard
        - application: prometheus
          endpoints:
          - metrics-endpoint
          - receive-remote-write
        - application: grafana
          endpoints:
          - grafana-dashboard
        - application: loki
          endpoints:
          - logging
      juju_model: cos
      retry_error_count: 5
      build_bundle: true
      trust_bundle: true
      bundles:
      - cos/cos.yaml
      - cos/overlay-cos-options.yaml
      - cos/overlay-cos-storage.yaml
      - cos/overlay-cos-offers.yaml
      wait_exclude:
      - scrape-interval-config-metrics
      - scrape-interval-config-monitors  
